---
title: "Data Management of DEPP cohort Evalaide - Matching"
author:
  - Pauline Martinot [UNICOG, NeuroSpin]
  - Bénédicte Colnet [Inria, Paris-Saclay]
date: "July 2021"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
abstract: | 
  This notebook concerns data from National assessment in 1st and 2nd grade in France : Matching. Reads the output of `13_Matching_script.R`.
---
# 2018 - DATA Matching

### Scenario 1

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2018" 
SCENARIO = 1
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 1){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P + T1_Resoud_Pb_P
                          + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "exact", 
                          discard = "both",
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```

### Scenario 2

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2018" 
SCENARIO = 2
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for"T1_Comp_Text_P"                     "T1_Compa_Lettres_P" _matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 2){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```


### Scenario 3

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2018" 
SCENARIO = 3
ESTIMAND = "ATT" # effect of being a girl

load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "T2_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO ==  3) {
  data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P + T2_Math + T2_Language, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
}


save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```






# 2019 - DATA

### Scenario 1

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2019" 
SCENARIO = 1
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 1){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P + T1_Resoud_Pb_P
                          + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "exact", 
                          discard = "both",
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```

### Scenario 2

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"

SCENARIO = 2
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 2){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```


### Scenario 3

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
SCENARIO = 3
ESTIMAND = "ATT" # effect of being a girl

load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching 
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "T2_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO ==  3) {
  data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P + T2_Math + T2_Language, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
}


save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData")) 
```


# 2020 - DATA

### Scenario 1

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2020" 
SCENARIO = 1
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 1){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P + T1_Resoud_Pb_P
                          + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "exact", 
                          discard = "both",
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```

### Scenario 2

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"

SCENARIO = 2
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 2){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```


### Scenario 3

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
SCENARIO = 3
ESTIMAND = "ATT" # effect of being a girl

load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching 
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "T2_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO ==  3) {
  data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P + T2_Math + T2_Language, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
}


save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData")) 
```


# 2021 - DATA

### Scenario 1

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
ANNEE_COHORTE = "2021" 
SCENARIO = 1
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 1){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P + T1_Resoud_Pb_P
                          + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "exact", 
                          discard = "both",
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```

### Scenario 2

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"

SCENARIO = 2
ESTIMAND = "ATT" # effect of being a girl

# Libraries
library(MatchIt)

# Data loading
load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP", "ID_Classe_CP")
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")
#data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe",
#"ID_Eleve", "T2_Lire_Text_Cut_P_Rank")]

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO == 2){
  data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "IPS_Etab_CP")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
} 

save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData"))
```


### Scenario 3

```{r}
knitr::opts_chunk$set(echo = TRUE)

# Seed because random sampling and matching
set.seed(123)

# Parameters to set before launch of the pipeline
IMPUTED = "imputed" # "imputed" "non-imputed"
SCENARIO = 3
ESTIMAND = "ATT" # effect of being a girl

load(paste0("~/Data/cohort_", ANNEE_COHORTE, "_", IMPUTED, "_joined_n.RData"))

Math_T1_P <- c("T1_Ecri_Nombre_P",
               "T1_Lire_Nombre_P",
               "T1_Resoud_Pb_P",
               "T1_Denombrer_P",
               "T1_Compa_Nombre_P",
               "T1_Ligne_Num_P")


# covariates_used_for_matching 
covariates_used_for_matching <- c(Math_T1_P, "T1_Language", "Categ_Etab_CP", "IPS_Etab_CP", "Age_CP")

data.to.match <- joined_n[, c(covariates_used_for_matching, "T1_Math", "T2_Math", "T3_Math", "Sexe", "T1_Language", "T2_Language", "ID_Eleve")]

data.to.match$Sexe <- ifelse(data.to.match$Sexe == "Girls", 1, 0)


if (SCENARIO ==  3) {
  data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language") ] <- round(data.to.match[, c("T1_Language", Math_T1_P, "T2_Math", "T2_Language")], 0)
  
  matched.data <- matchit(Sexe ~ Categ_Etab_CP + IPS_Etab_CP + Age_CP + T1_Language + T1_Ecri_Nombre_P + T1_Lire_Nombre_P +
                            T1_Resoud_Pb_P + T1_Denombrer_P + T1_Compa_Nombre_P + T1_Ligne_Num_P + T2_Math + T2_Language, 
                          method = "cem", 
                          cutpoints = list(IPS_Etab_CP = 10, Age_CP = 4), # IPS binned in 10, and age tolerate to 4 months
                          k2k = TRUE,
                          grouping = list(Categ_Etab_CP = list(c("Public", "Private"), c("REP", "REP+"))),
                          estimand = ESTIMAND,
                          data = data.to.match)  
  
}


save.image(file = paste0("~/Data/output_13_Matching_", IMPUTED, "_", ANNEE_COHORTE, "_SCENARIO_", SCENARIO, "_", ESTIMAND, ".RData")) 

```


